# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal
    - name: Publish
      run: dotnet publish src/HomeAutomation.csproj --no-build -c Release -o ./out
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker
      uses: docker/login-action@v3
      with:
        registry: "${{ vars.DOCKER_REGISTRY }}"
        username: "${{ vars.DOCKER_USER }}"
        password: "${{ secrets.DOCKER_PASS }}"
    - name: Build and push Docker image
      run: docker buildx build -t ${{ vars.DOCKER_IMAGE }}:latest -t ${{ vars.DOCKER_IMAGE }}:${{ github.sha }} --provenance=false --push .
